plugins {
    id 'idea'
    id 'maven-publish'
    id 'fabric-loom' version '1.10-SNAPSHOT'
}

version = '1.21.1-8.0.14'
group = 'com.blakebr0.cucumber'

base {
    archivesName = 'Cucumber'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

configurations {
//    runtimeClasspath.extendsFrom localRuntime
}

loom {
    accessWidenerPath = file('src/main/resources/cucumber.accesswidener')
}

repositories {
    flatDir {
        dirs 'libs'
    }
    maven {
        url = 'https://maven.blamejared.com/'
        content {
            includeGroup "com.almostreliable.mods"
        }
    }
    maven {
        url = 'https://mvn.devos.one/snapshots'
    }
}

dependencies {
    minecraft("com.mojang:minecraft:${minecraft_version}")
    mappings(loom.officialMojangMappings())
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    include modApi("teamreborn:energy:${energy_version}")
    modCompileOnly "com.almostreliable.mods:almostunified-fabric:${almostunified_version}"

        for (String module in porting_lib_modules.split(",")) {
            modImplementation("io.github.fabricators_of_create.Porting-Lib:$module:${porting_lib_version}+${minecraft_version}") {{
                exclude group: 'com.github.Chocohead'
            }
        }
    }

    tasks.withType(ProcessResources).configureEach {
        var replaceProperties = [
                mod_version: version.split('-').last(),
        ]
        inputs.properties replaceProperties

        filesMatching(['META-INF/neoforge.mods.toml']) {
            expand replaceProperties
        }
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            artifact jar
        }
    }

    repositories {
        maven {
            url = 'https://maven.blakesmods.com'

            credentials {
                username = System.getenv('BLAKESMODS_MAVEN_USERNAME')
                password = System.getenv('BLAKESMODS_MAVEN_PASSWORD')
            }

            authentication {
                basic(BasicAuthentication)
            }
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}